kitchen/urls.py
from django.urls import path

from kitchen.views import index, CookListView, DishListView, DishTypeListView, DishDetailView, CookCreateView, \
    UserLogoutView, UserLoginView, DishCreateView, toggle_assign_to_dish, DishTypeCreateView

urlpatterns = [
    path("", index, name="index"),
    path("cooks/", CookListView.as_view(), name="cook-list"),
    path("menu/", DishListView.as_view(), name="menu"),
    path("dish_types/", DishTypeListView.as_view(), name="dish-types"),
    path("dish_detail/<int:pk>/", DishDetailView.as_view(), name="dish-detail"),
    path("cooks/create_cooks/", CookCreateView.as_view(), name="create-cooks"),
    path("menu/create_dish/", DishCreateView.as_view(), name="create-dish"),
    path("dish_types/create_dishtype/", DishTypeCreateView.as_view(), name="create-dish-type"),
    path(
        "menu/<int:pk>/toggle-assign/",
        toggle_assign_to_dish,
        name="toggle-dish-assign",
    ),
    path("login/", UserLoginView.as_view(), name="user-login"),
    path("logout/", UserLogoutView.as_view(), name="user-logout"),
]
app_name = "kitchen"

restaurant_kitchen_service/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("kitchen.urls", namespace="kitchen")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

kitchen/models.py
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinValueValidator
from django.db import models


# Create your models here.
class DishType(models.Model):
    name = models.CharField(max_length=63)

    def __str__(self):
        return f"{self.name}"


class Cook(AbstractUser):
    years_of_experience = models.IntegerField(blank=False, null=True, validators=[
        MinValueValidator(1)
    ])

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"


class Dish(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(max_length=1000)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    dish_type = models.ForeignKey(DishType, on_delete=models.CASCADE)
    cooks = models.ManyToManyField(Cook, related_name="dishes")  # Assuming this is how you have set up the relationship

    def __str__(self):
        return f"{self.name}"

kitchen/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

from kitchen.models import Cook, Dish, DishType


class DishSearchForm(forms.Form):
    model = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by dish"
            }
        )
    )


class DishTypeSearchForm(forms.Form):
    model = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by dish type"
            }
        )
    )


class CookCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Cook
        fields = UserCreationForm.Meta.fields + (
            "years_of_experience",
            "first_name",
            "last_name",
        )

    def clean_years_of_experience(self):
        return check_years_of_experience(self.cleaned_data["years_of_experience"])


def check_years_of_experience(years_of_experience):
    if not isinstance(years_of_experience, int):
        raise ValueError('Input correct value')
    if years_of_experience < 1:
        raise ValidationError('Minimum value for years of experience is 1!')
    return years_of_experience


class DishCreationForm(forms.ModelForm):
    class Meta:
        model = Dish
        fields = "__all__"


class DishTypeForm(forms.ModelForm):
    class Meta:
        model = DishType
        fields = "__all__"

kitchen/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.views import LoginView, LogoutView
from kitchen.forms import DishSearchForm, CookCreationForm, DishCreationForm, DishTypeForm

from kitchen.models import DishType, Dish, Cook


# Create your views here.
def index(request):
    dish_type = DishType.objects.all()

    context = {
        "dish_type": dish_type
    }
    return render(request, "kitchen/index.html", context=context)


class DishTypeListView(LoginRequiredMixin, generic.ListView):
    model = DishType
    context_object_name = "dish_types"
    template_name = "kitchen/dish_types.html"
    paginate_by = 10


class DishTypeDetailView(generic.DetailView):
    model = DishType


class CookListView(LoginRequiredMixin, generic.ListView):
    model = Cook
    paginate_by = 5


class CookCreateView(LoginRequiredMixin, generic.CreateView):
    model = Cook
    form_class = CookCreationForm
    success_url = reverse_lazy("kitchen:cook-list")


class CookDetailView(generic.DetailView):
    model = Cook


class DishListView(LoginRequiredMixin, generic.ListView):
    model = Dish
    paginate_by = 3
    template_name = "kitchen/menu.html"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(DishListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = DishSearchForm(
            initial={"name": name}
        )
        return context


class DishCreateView(LoginRequiredMixin, generic.CreateView):
    model = Dish
    form_class = DishCreationForm
    success_url = reverse_lazy("kitchen:menu")


class DishDetailView(generic.DetailView):
    model = Dish
    queryset = Dish.objects.select_related('dish_type').prefetch_related('cooks')


class DishTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = DishType
    form_class = DishTypeForm
    success_url = reverse_lazy("kitchen:dish-types")


class UserLoginView(LoginView):
    template_name = "registration/login.html"
    success_url = reverse_lazy("kitchen:index")


class UserLogoutView(LogoutView):
    template_name = "registration/register.html"
    success_url = reverse_lazy("kitchen:index")


@login_required
def toggle_assign_to_dish(request, pk):
    cook = Cook.objects.get(id=request.user.id)
    dish = Dish.objects.get(id=pk)

    if dish in cook.dishes.all():
        cook.dishes.remove(dish)
    else:
        cook.dishes.add(dish)

    return HttpResponseRedirect(reverse_lazy("kitchen:dish-detail", args=[pk]))

templates/accounts/login.html
{% extends "layouts/base.html" %}

{% block title %} Sign IN {% endblock %} 

{% block body_class %} sign-in-basic {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  {% include 'includes/navigation-transparent.html' %} 
  
  <div class="page-header align-items-start min-vh-100" style="background-image: url('https://images.unsplash.com/photo-1497294815431-9365093b7331?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1950&q=80');" loading="lazy">
    <span class="mask bg-gradient-dark opacity-6"></span>
    <div class="container my-auto">
      <div class="row">
        <div class="col-lg-4 col-md-8 col-12 mx-auto">
          <div class="card z-index-0 fadeIn3 fadeInBottom">
            <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
              <div class="bg-gradient-primary shadow-primary border-radius-lg py-3 pe-1">
                <h4 class="text-white font-weight-bolder text-center mt-2 mb-0">
                  Django Material Kit
                </h4>
                <div class="row mt-3">
                  <p class="mb-0 text-white text-center">
                    {% if msg %}
                      {{ msg | safe }}
                    {% else %}
                      Add your credentials
                    {% endif %}
                  </p>
                </div>
              </div>
            </div>
            <div class="card-body">
              <form role="form" method="post" action="" class="text-start">

                {% csrf_token %}

                <div class="input-group input-group-outline mb-3">
                    {{ form.username }}
                </div>
                <div class="input-group input-group-outline mb-3">
                  {{ form.password }}
                </div>
                <div class="form-check form-switch d-flex align-items-center mb-3">
                  <input class="form-check-input" type="checkbox" id="rememberMe">
                  <label class="form-check-label mb-0 ms-2" for="rememberMe">Remember me</label>
                </div>
                <div class="text-center">
                  <button type="submit" name="login" 
                          class="btn bg-gradient-primary w-100 my-4 mb-2">Sign in</button>
                </div>
                <p class="mt-4 text-sm text-center">
                  Don't have an account?
                  <a href="{% url 'register' %}" class="text-primary text-gradient font-weight-bold">Sign UP</a>
                </p>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>

    {% include 'includes/footer-auth.html' %} 

  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

templates/includes/navigation-light.html
  <!-- Navbar Light -->
  <nav class="navbar navbar-expand-lg navbar-light bg-white py-3">
    <div class="container">
      <a class="navbar-brand font-weight-bolder ms-sm-3" href="/" rel="tooltip" title="Designed and Coded by Creative Tim" data-placement="bottom">
              Restaurant
            </a>
      <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-
        icon mt-2">
          <span class="navbar-toggler-bar bar1"></span>
          <span class="navbar-toggler-bar bar2"></span>
          <span class="navbar-toggler-bar bar3"></span>
        </span>
      </button>
      <div class="collapse navbar-collapse w-100 pt-3 pb-2 py-lg-0 ms-lg-12 ps-lg-5" id="navigation">
        <ul class="navbar-nav navbar-nav-hover ms-auto">
          <li class="nav-item dropdown dropdown-hover mx-2 ms-lg-5">
            <a class="nav-link ps-2 d-flex justify-content-between cursor-pointer align-items-center" id="dropdownMenuPages5" data-bs-toggle="dropdown" aria-expanded="false">
              <i class="material-icons opacity-6 me-2 text-md">dashboard</i>
                    Menu
                    <img src="{{ ASSETS_ROOT }}/static/img/down-arrow-dark.svg" alt="down-arrow" class="arrow ms-auto ms-md-2">
                  </a>
                  <div class="dropdown-menu dropdown-menu-animation ms-n3 dropdown-md p-3 border-radius-xl mt-0 mt-lg-3" aria-labelledby="dropdownMenuPages">
                    <div class="d-none d-lg-block">
                      <h6 class="dropdown-header text-dark font-weight-bolder d-flex align-items-center px-1">
                        Landing Pages
                      </h6>
                      <a href="{% url 'kitchen:dish-types' %}" class="dropdown-item border-radius-md">
                        <span>Dish types</span>
                      </a>
                      <a href="{% url 'kitchen:menu' %}" class="dropdown-item border-radius-md">
                        <span>Dishes</span>
                      </a>
                      <a href="{% url 'kitchen:cook-list' %}" class="dropdown-item border-radius-md">
                        <span>Our cooks</span>
                      </a>
                      <h6 class="dropdown-header text-dark font-weight-bolder d-flex align-items-center px-1 mt-3">
                        Account
                      </h6>
                      <a href="{% url 'kitchen:user-login' %}
" class="dropdown-item border-radius-md">
                        <span>Sign In</span>
                      </a>
                    </div>
									</div>
					</li>


                
        </ul>
      </div>
    </div>
  </nav>

templates/includes/navigation.html
  <!-- Navbar -->
  <div class="container position-sticky z-index-sticky top-0">
    <div class="row">
      <div class="col-12">
        <nav class="navbar navbar-expand-lg  blur border-radius-xl mt-4 top-0 z-index-3 shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
          <div class="container-fluid px-0">
            <a class="navbar-brand font-weight-bolder ms-sm-3" href="/" rel="tooltip" title="Designed and Coded by Creative Tim" data-placement="bottom">
              Restaurant
            </a>
            <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon mt-2">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </span>
            </button>
            <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0 w-100" id="navigation">
              <ul class="navbar-nav navbar-nav-hover ms-auto">
                <li class="nav-item dropdown dropdown-hover mx-2">
                  <a class="nav-link ps-2 d-flex cursor-pointer align-items-center" id="dropdownMenuPages" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="material-icons opacity-6 me-2 text-md">dashboard</i>
                    Menu
                    <img src="{{ ASSETS_ROOT }}/static/img/down-arrow-dark.svg" alt="down-arrow" class="arrow ms-auto ms-md-2">
                  </a>
                  <div class="dropdown-menu dropdown-menu-animation ms-n3 dropdown-md p-3 border-radius-xl mt-0 mt-lg-3" aria-labelledby="dropdownMenuPages">
                    <div class="d-none d-lg-block">
                      <h6 class="dropdown-header text-dark font-weight-bolder d-flex align-items-center px-1">
                        Landing Pages
                      </h6>
                      <a href="{% url 'kitchen:dish-types' %}" class="dropdown-item border-radius-md">
                        <span>Dish types</span>
                      </a>
                      <a href="{% url 'kitchen:menu' %}" class="dropdown-item border-radius-md">
                        <span>Dishes</span>
                      </a>
                      <a href="{% url 'kitchen:cook-list' %}" class="dropdown-item border-radius-md">
                        <span>Our cooks</span>
                      </a>
                      <h6 class="dropdown-header text-dark font-weight-bolder d-flex align-items-center px-1 mt-3">
                        Account
                      </h6>
                      <a href="{% url 'kitchen:user-login' %}" class="dropdown-item border-radius-md">
                        <span>Sign In</span>
                      </a>
                    </div>
                {% if request.user.is_authenticated %}
                  <li class="nav-item ms-lg-auto">
                    <a class="nav-link nav-link-icon me-2"
                      href="{% url 'kitchen:user-logout' %}">
                      <i class="fa fa-sign-out me-1"></i>
                      <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Sign OUT">Logout</p>
                    </a>
                  </li>
                {% endif %}
								{% if not request.user.is_authenticated %}
                  <li class="nav-item ms-lg-auto">
                    <a class="nav-link nav-link-icon me-2"
                      href="{% url 'kitchen:user-login' %}">
                      <i class="fa fa-sign-out me-1"></i>
                      <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Login">Login</p>
                    </a>
                  </li>
                {% endif %}
								</div>
              </ul>
            </div>
          </div>
        </nav>
        <!-- End Navbar -->
      </div>
    </div>
  </div>

templates/kitchen/cook_form.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} cook</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/kitchen/cook_list.html
{% extends "layouts/base.html" %}

{% block title %} Blog Author {% endblock %}

{% block body_class %} blog-author {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  {% include 'includes/navigation.html' %}

  <header>
    <div class="page-header min-height-400" style="background-image: url('{{ ASSETS_ROOT }}static/img/city-profile.jpg');" loading="lazy">
      <span class="mask bg-gradient-dark opacity-8"></span>
    </div>
  </header>

  <div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6 mb-4">
    <!-- START Testimonials w/ user image & text & info -->
    {% if cook_list %}
			{% for cook in cook_list %}
			<section class="py-sm-7 py-5 position-relative">
      	<div class="container">
        	<div class="row">
          	<div class="col-12 mx-auto">
            	<div class="mt-n8 mt-md-n9 text-center">
              	<img class="avatar avatar-xxl shadow-xl position-relative z-index-2" src="{{ ASSETS_ROOT }}/static/img/bruce-mars.jpg" alt="bruce" loading="lazy">
            	</div>
            <div class="row py-5">
              <div class="col-lg-7 col-md-7 z-index-2 position-relative px-md-2 px-sm-5 mx-auto">
                <div class="d-flex justify-content-between align-items-center mb-2">
									<table>
                  <tr>
										<th><h3 class="mb-0">{{ cook.first_name }} {{ cook.last_name }}</h3></th></tr>
										</table>
                  <div class="d-block">
                    <button type="button" class="btn btn-sm btn-outline-info text-nowrap mb-0"><a href="{% url 'kitchen:create-cooks' %}">Create</a></button>
                  </div>
                </div>
                <div class="row mb-4">
                  <div class="col-auto">
                    <span>Years of experience:</span>
										<span class="h6">{{ cook.years_of_experience }}</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  	</div>
			{% endfor %}
	{% endif %}

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

templates/kitchen/dish_detail.html
{% extends "layouts/base.html" %}

{% block title %} Blog Author {% endblock %}

{% block body_class %} blog-author {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  {% include 'includes/navigation-light.html' %}

  <header>
    <div class="page-header min-height-400" style="background-image: url('{{ ASSETS_ROOT }}/img/city-profile.jpg');" loading="lazy">
      <span class="mask bg-gradient-dark opacity-8"></span>
    </div>
  </header>

	<div class="card card-body blur shadow-blur mx-3 mx-md-4 mt-n6 mb-4">
    <!-- START Testimonials w/ user image & text & info -->
    <section class="py-sm-7 py-5 position-relative">
      <div class="container">
        <div class="row">
          <div class="col-12 mx-auto">
            <div class="mt-n8 mt-md-n9 text-center">
            </div>
            <div class="row py-5">
              <div class="col-lg-7 col-md-7 z-index-2 position-relative px-md-2 px-sm-5 mx-auto">
                <div class="d-flex justify-content-between align-items-center mb-2">
                  <h3 class="mb-0">{{ dish.name }}</h3>
                </div>
								{% if dish in user.dishes.all %}
      						<a href="{% url 'kitchen:toggle-dish-assign' pk=dish.id %}" class="btn btn-danger link-to-page">
        					Delete me from this dish
      						</a>
    						{% else %}
      						<a href="{% url 'kitchen:toggle-dish-assign' pk=dish.id %}" class="btn btn-success link-to-page">
        					Assign me to this dish
									</a>
    						{% endif %}
								<div class="row mb-4">
                  <div class="col-auto">
                    <span>Price: {{ dish.price }}</span>
                  </div>
                </div>
									<p class="text-lg mb-0">
										{{ dish.description }}
										<br><a href="javascript:;" class="text-info icon-move-right">
                  	</a>
                	</p>
									<p class="text-lg mb-0">
									Cooks:
										{% for cook in dish.cooks.all %}
											{{ cook.first_name }} {{ cook.last_name }}
										{% endfor %}
									</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>




{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

templates/kitchen/dish_types.html
<!--
=========================================================
* Material Kit 2 - v3.0.0
=========================================================

* Product Page: https://appseed.us/product/django-material-kit
* Copyright 2021 Creative Tim (https://www.creative-tim.com)
* Licensed under MIT (https://www.creative-tim.com/license)
* Coded by Creative Tim

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software. -->
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="apple-touch-icon" sizes="76x76" href="{{ ASSETS_ROOT }}/static/img/apple-icon.png">
  <link rel="icon" type="image/png" href="{{ ASSETS_ROOT }}/static/img/favicon.png">

  <title>
    Django Material Kit 2 - Features | AppSeed
  </title>

  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700" />
  <!-- Nucleo Icons -->
  <link href="{{ ASSETS_ROOT }}/static/css/nucleo-icons.css" rel="stylesheet" />
  <link href="{{ ASSETS_ROOT }}/static/css/nucleo-svg.css" rel="stylesheet" />
  <!-- Font Awesome Icons -->
  <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
  <!-- Material Icons -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">
  <!-- CSS Files -->
  <link id="pagestyle" href="{{ ASSETS_ROOT }}/static/css/material-kit.css?v=3.0.0" rel="stylesheet" />

</head>
<body class="features-sections">

  {% include 'includes/navigation-light.html' %}

  <div class="container mt-5">
    <div class="row">
      <div class="col-lg-12 mx-auto">
        <div class="mb-4 w-100 w-md-50 w-lg-25">
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item active" aria-current="page">Dish Type</li>
            </ol>
          </nav>
        </div>
        <div class="position-relative border-radius-xl overflow-hidden shadow-lg mb-7">
            <div class="row justify-space-between py-2">
              <div class="col-lg-3">
                <div class="nav-wrapper position-relative end-0">
									{% for dish_type in dish_types %}
										<p class="lead text-dark pt-1 mb-0">~ <a href={% url "kitchen:menu" %}>{{ dish_type.name }}</a></p><br>
									{% endfor %}
                </div>
              </div>
          </div>
				<div class="d-block">
                    <button type="button" class="btn btn-sm btn-outline-info text-nowrap mb-0"><a href="{% url 'kitchen:create-dish-type' %}">Create</a></button>
                  </div>
          <div class="tab-content tab-space">
            <div class="tab-pane active" id="preview-features-1">
              <iframe class="w-100 height-600" srcdoc='<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"'>

							</iframe>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>


  {% include 'includes/scripts.html' %} 

</body>
</html>

templates/kitchen/menu.html
{% load crispy_forms_filters %}
{% load query_transform %}
<!--
=========================================================
* Material Kit 2 - v3.0.0
=========================================================

* Product Page: https://appseed.us/product/django-material-kit
* Copyright 2021 Creative Tim (https://www.creative-tim.com)
* Licensed under MIT (https://www.creative-tim.com/license)
* Coded by Creative Tim

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software. -->
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="apple-touch-icon" sizes="76x76" href="{{ ASSETS_ROOT }}/static/img/apple-icon.png">
  <link rel="icon" type="image/png" href="{{ ASSETS_ROOT }}/static/img/favicon.png">

  <title>
    Django Material Kit 2 - Features | AppSeed
  </title>

  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700" />
  <!-- Nucleo Icons -->
  <link href="{{ ASSETS_ROOT }}/static/css/nucleo-icons.css" rel="stylesheet" />
  <link href="{{ ASSETS_ROOT }}/static/css/nucleo-svg.css" rel="stylesheet" />
  <!-- Font Awesome Icons -->
  <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
  <!-- Material Icons -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">
  <!-- CSS Files -->
  <link id="pagestyle" href="{{ ASSETS_ROOT }}/static/css/material-kit.css?v=3.0.0" rel="stylesheet" />

</head>
<body class="features-sections">

  {% include 'includes/navigation-light.html' %}

  <div class="container mt-5">
    <div class="row">
      <div class="col-lg-12 mx-auto">
        <div class="mb-4 w-100 w-md-50 w-lg-25">
					<div class="input-group rounded">
  	<input type="search" class="form-control rounded" placeholder="Search" aria-label="Search" aria-describedby="search-addon" />
		<span class="input-group-text border-0" id="search-addon">
    	<i class="fas fa-search"></i>
  	</span>
	</div>
          <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item active" aria-current="page">Menu</li>
						</ol>
          </nav>
        </div>
        <div class="position-relative border-radius-xl overflow-hidden shadow-lg mb-7">
            <div class="row justify-space-between py-2">
              <div>
                <div class="nav-wrapper position-relative end-0">
										{% for dish in dish_list %}
											<p class="lead text-dark pt-3 mb-2"><a href="{% url 'kitchen:dish-detail' pk=dish.id %}">{{ dish.name }}</a>:<p class="text-dark mb-2">{{ dish.description }}</p><br>
										{% endfor %}
                </div>
              </div>
          </div>
				<div class="d-block">
                    <button type="button" class="btn btn-sm btn-outline-info text-nowrap mb-0"><a href="{% url 'kitchen:create-dish' %}">Create</a></button>
                  </div>
          <div class="tab-content tab-space">
            <div class="tab-pane active" id="preview-features-1">
              <iframe class="w-100 height-600" srcdoc='<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"'>

							</iframe>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>


  {% include 'includes/scripts.html' %} 

</body>
</html>